### PR TITLE
Recipe for v0.20.1

### PR DESCRIPTION
**Pull request by registerrier**
Checklist
* [x ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by bsipocz** [comment]
@registerrier - a new release should be picked up automatically, doesn't the machinery work for gammapy (it usually takes up to a few hours for a PR to appear after the release lands on PyPI)?

**Comment by registerrier** [comment]
> @registerrier - a new release should be picked up automatically, doesn't the machinery work for gammapy (it usually takes up to a few hours for a PR to appear after the release lands on PyPI)?

@bsipocz I am not sure the machinery works for gammapy. At least, the last releases were not automatic.

**Comment by bsipocz** [comment]
As I see the dates on the PRs you haven't waited long enough, sometimes it takes a few hours for the bot to catch up with PyPI. But I don't see a reason why it stopped doing the auto-updates, it used to work for this repo.

**Pull request merged**
