### PR TITLE
Enable macos arm64 builds, compile against oldest supported numpy

### PR DESCRIPTION
**Pull request by maxnoe**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwcraig** [comment]
Closing/reopening to re-run the CI

**Comment by maxnoe** [comment]
@mwcraig the regions packages is still not available due to the conda cdn outage: 

https://github.com/conda-forge/status/issues/114#issuecomment-854886393

**Comment by mwcraig** [comment]
Thanks -- sounds like it will still be a little while until it is back.

**Comment by maxnoe** [comment]
@mwcraig the regions package is now available, pyerfa still missing

**Comment by mwcraig** [comment]
Thanks, @maxnoe!

**Pull request merged**
