### PR TITLE
Build for v0.20

### PR DESCRIPTION
**Pull request by registerrier**
Checklist
* [x ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
@registerrier -- I think the pip release yesterday may have broken things. Can you try restricting pip to `<22.1` to see if that fixes t prob?

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
That is progress -- it looks like the issue now is that the license file is not where the recipe expects it to be.

**Comment by registerrier** [comment]
@conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
You might want to change the `pip` pin to `pip !=22.1` so that when a new pip is released you will pick that up. Based on the discussion in https://github.com/pypa/pip/issues/11116 it sounds like this will be fixed in pip.

**Comment by adonath** [comment]
Thanks a lot @mwcraig for your help!

**Pull request merged**
