### PR TITLE
Update meta.yaml for v0.7 release

### PR DESCRIPTION
**Pull request by cdeil**

### CODE REVIEW

**Comment by cdeil** [comment]
@bsipocz @mwcraig - How is the list under `test` -> `imports` generated? Is there a way to generate or update it automatically?

**Comment by cdeil** [comment]
The Windows builds on Python 2.7 and 3.6 (but now 3.5!?) are failing like this: 
https://ci.appveyor.com/project/conda-forge/gammapy-feedstock/build/1.0.3
```
The batch file cannot be found.
```
Anyone know why? What to do?

**Comment by cdeil** [comment]
Why have the conda packages showed up at https://anaconda.org/conda-forge/gammapy/files even though this PR isn't merged yet. Is this normal?

**Comment by bsipocz** [comment]
@cdeil - I would guess (but it's only a guess) that the builds are pushed up as you've opened the branch in the main repo rather than on your fork. My understanding is that package builds from all branches will end up in the conda-forge channel...

**Comment by bsipocz** [comment]
(and yes, it's a rather annoying github bug that one with commit right cannot edit on github as in that case the branch will be opened in the main repo and cannot be forced to be on the fork instead (at least I didn't find a way to force it that way))

**Comment by cdeil** [comment]
Does anyone know why the Windows build fails? (see comment above?)

**Comment by bsipocz** [comment]
@conda-forge-admin, please rerender

**Comment by bsipocz** [comment]
@cdeil - it probably needs rerendering, at least that was a solution for similar failures in other repos.

**Comment by cdeil** [comment]
I see that the build for travis-ci and appveyor here was cancelled. Anyone know why? Should it be re-started?

**Comment by bsipocz** [comment]
@cdeil -  I guess someone cancelled them. Opening a PR from a branch of the repo double triggers both CIs, and the push ones will be triggered again after the merge anyway. I think it's safe to merge this now as the PR builds are passing.

**Pull request merged**
